/* SVN FILE: $Id: NamesStaging.java 7368 2013-05-23 20:11:49Z llg5 $ */
package edu.psu.iam.cpr.core.database.beans;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 United States License. To
 * view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/us/ or send a letter to Creative
 * Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
 *
 * @package edu.psu.iam.cpr.core.database.beans
 * @author $Author: llg5 $
 * @version $Rev: 7368 $
 * @lastrevision $Date: 2013-05-23 16:11:49 -0400 (Thu, 23 May 2013) $
 */

@Entity
@Table(name="names_staging")
public class NamesStaging implements Serializable {

        /** Contains the serialized UID */
        private static final long serialVersionUID = 1L;

        /** Contains the first name of the person. */
        @Column(name="first_name", nullable=true, length=60)
        private String firstName;

        /** Source system the import was from. */
        @Column(name="import_from", nullable=true, length=30)
        private String importFrom;

        /** Contains the suffix, if any. */
        @Column(name="suffix", nullable=true, length=30)
        private String suffix;

        /** Contains a unique number that identifies a person. */
        @Column(name="person_id", nullable=false)
        private Long personId;

        /** Contains the match code generated by the match code service for the name. */
        @Column(name="name_match_code", nullable=true, length=60)
        private String nameMatchCode;

        /** Contains a unique number that identifies a record in the names staging table.  It is populated by the seq_names_staging sequence. */
        @Id
        @Column(name="name_staging_key", nullable=false)
        @GeneratedValue(strategy=GenerationType.AUTO, generator="seq_names_staging")
        @SequenceGenerator(name="seq_names_staging", sequenceName="seq_names_staging", allocationSize = 1, initialValue= 1)
        private Long nameStagingKey;

        /** Date record was imported by batch processing. */
        @Column(name="import_date", nullable=true)
        private Date importDate;

        /** Contains the last name of the person. */
        @Column(name="last_name", nullable=true, length=60)
        private String lastName;

        /** Contains the middle name of the person, if applicable. */
        @Column(name="middle_names", nullable=true, length=60)
        private String middleNames;

        /**
         * Constructor
         */
        public NamesStaging() {
            super();
        }

        /**
         * @return the firstName
         */
        public String getFirstName() {
                return firstName;
        }

        /**
         * @param firstName the firstName to set.
         */
        public void setFirstName(String firstName) {
                this.firstName = firstName;
        }

        /**
         * @return the importFrom
         */
        public String getImportFrom() {
                return importFrom;
        }

        /**
         * @param importFrom the importFrom to set.
         */
        public void setImportFrom(String importFrom) {
                this.importFrom = importFrom;
        }

        /**
         * @return the suffix
         */
        public String getSuffix() {
                return suffix;
        }

        /**
         * @param suffix the suffix to set.
         */
        public void setSuffix(String suffix) {
                this.suffix = suffix;
        }

        /**
         * @return the personId
         */
        public Long getPersonId() {
                return personId;
        }

        /**
         * @param personId the personId to set.
         */
        public void setPersonId(Long personId) {
                this.personId = personId;
        }

        /**
         * @return the nameMatchCode
         */
        public String getNameMatchCode() {
                return nameMatchCode;
        }

        /**
         * @param nameMatchCode the nameMatchCode to set.
         */
        public void setNameMatchCode(String nameMatchCode) {
                this.nameMatchCode = nameMatchCode;
        }

        /**
         * @return the nameStagingKey
         */
        public Long getNameStagingKey() {
                return nameStagingKey;
        }

        /**
         * @param nameStagingKey the nameStagingKey to set.
         */
        public void setNameStagingKey(Long nameStagingKey) {
                this.nameStagingKey = nameStagingKey;
        }

        /**
         * @return the importDate
         */
        public Date getImportDate() {
                return importDate;
        }

        /**
         * @param importDate the importDate to set.
         */
        public void setImportDate(Date importDate) {
                this.importDate = importDate;
        }

        /**
         * @return the lastName
         */
        public String getLastName() {
                return lastName;
        }

        /**
         * @param lastName the lastName to set.
         */
        public void setLastName(String lastName) {
                this.lastName = lastName;
        }

        /**
         * @return the middleNames
         */
        public String getMiddleNames() {
                return middleNames;
        }

        /**
         * @param middleNames the middleNames to set.
         */
        public void setMiddleNames(String middleNames) {
                this.middleNames = middleNames;
        }

}
